[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tqdm_vendored/_dist_ver.py"
write_to_template = "__version__ = '{version}'\n"

[tool.setuptools.packages.find]
exclude = ["benchmarks", "examples", "tests", "wiki", "docs", "feedstock"]

[project.urls]
homepage = "https://tqdm.github.io"
repository = "https://github.com/tqdm/tqdm"
changelog = "https://tqdm.github.io/releases"
wiki = "https://github.com/tqdm/tqdm/wiki"

[project]
name = "tqdm_vendored"
version = "4.61.1"
maintainers = [{ name = "tqdm developers", email = "devs@tqdm.ml" }]
description = "Fast, Extensible Progress Meter"
requires-python = ">=3.4"
license = { text = "MPL-2.0 AND MIT" }
